### ISSUE TITLE
Unit Problem by using SpectrumList

### ISSUE THREAD

**Issue by philipp128** [skypyproject/skypy#384]
**Describe the bug**
By calculating the magnitudes in at least two bandpasses of the same bandpass filter system skypy returns `AttributeError: 'SpectrumList' object has no attribute 'unit'`. This happens by using the version on the current master branch.

**To Reproduce**
1) Install the current master branch version of `skypy`
2) Include the magnitude calculation in at least two bands of the same filter system into the yaml file
Take for example:
```
cosmology: !astropy.cosmology.FlatLambdaCDM
  H0: 70
  Om0: 0.3
mag_lim: 35
sky_area: 0.5329 deg2
z_range: !numpy.arange [0, 3.01, 0.1]
M_star_blue: !astropy.modeling.models.Linear1D [-0.417, -20.591]
phi_star_blue: !astropy.modeling.models.Exponential1D [0.0063, -3.78788]
alpha_blue: -1.3
M_star_red: !astropy.modeling.models.Linear1D [-0.610, -20.416]
phi_star_red: !astropy.modeling.models.Exponential1D [0.0141, -0.44803]
alpha_red: -0.5
tables:
  blue:
    z, M: !skypy.galaxy.schechter_lf
      redshift: $z_range
      M_star: $M_star_blue
      phi_star: $phi_star_blue
      alpha: $alpha_blue
      m_lim: $mag_lim
      sky_area: $sky_area
    distmod: !skypy.galaxy.luminosity.distance_modulus
      redshift: $blue.z
    coeff: !skypy.galaxy.spectrum.dirichlet_coefficients
      redshift: $blue.z
      alpha0: [2.079, 3.524, 1.917, 1.992, 2.536]
      alpha1: [2.265, 3.862, 1.921, 1.685, 2.480]
      weight: [3.47e+09, 3.31e+06, 2.13e+09, 1.64e+10, 1.01e+09]
    stellar_mass: !skypy.galaxy.spectrum.stellar_mass_from_reference_band
      magnitudes: $blue.M
      coefficients: $blue.coeff
      templates: kcorrect_spec
      bandpass: bessell_B
    mag_g, mag_r: !skypy.galaxy.spectrum.magnitudes_from_templates
      coefficients: $blue.coeff
      templates: kcorrect_spec
      bandpass: decam2014_gr
      redshift: $blue.z
      stellar_mass: $blue.stellar_mass
      distance_modulus: $blue.distmod
```

3) run the file as normal with `skypy path/to/file --format fits`
4) Error specified above will occur

**Expected behavior**
It should run without throwing an error.
