### ISSUE TITLE
NameError: name 'speclite' is not defined

### ISSUE THREAD

**Issue by Lucia-Fonseca** [skypyproject/skypy#436]
**Describe the bug**
The problem occurs when the SkyPy pipeline tries to execute the `skypy.galaxies.spectrum.kcorrect.stellar_mass` function (line 18 in galaxies.yaml):
```
cosmology: !astropy.cosmology.FlatLambdaCDM
  H0: 70
  Om0: 0.3
tables:
  SF:
    z, M_B: !skypy.galaxies.schechter_lf
      redshift: !numpy.geomspace [0.01, 3.01, 3]
      M_star: -20.485
      phi_star: 0.00312608
      alpha: -1.29
      m_lim: 30
      sky_area: 10 deg2
    coeff: !skypy.galaxies.spectrum.dirichlet_coefficients
      redshift: $SF.z
      alpha0: [2.079, 3.524, 1.917, 1.992, 2.536]
      alpha1: [2.265, 3.862, 1.921, 1.685, 2.480]
      weight: [3.47e+09, 3.31e+06, 2.13e+09, 1.64e+10, 1.01e+09]
    sm: !skypy.galaxies.spectrum.kcorrect.stellar_mass
      coefficients: $SF.coeff
      magnitudes: $SF.M_B
      filter: bessell-B
```

**To Reproduce**
1. From a fresh environment, I installed SkyPy 0.4 and the latest version of Python 3.8.5
2. In a Jupyter notebook, I imported `SkyPy.pipeline.Pipeline`
3. I ran the code 
``` { .python}
   >>> from skypy.pipeline import Pipeline
   >>> sim = Pipeline.read('galaxies.yaml')
   >>> sim.execute()
```
4. Got error `NameError: name 'speclite' is not defined`.

**Expected behaviour**
I would expect SkyPy to install all dependencies. However, since this is an optional package, I would expect to raise and `ImportError`.

**System Details**
macOS-11.2.1
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
SkyPy 0.4

**Solution**
I installed the `speclite` package 
``` python3 -m pip install speclite```
and the error disappeared.
